name: Run Type Check
description: Run mypy

runs:
  using: composite
  steps:
    - name: Detect folders to typecheck
      id: paths
      run: |
        PATHS="src"

        if [ -d "tests" ]; then
          PATHS="$PATHS tests"
        fi

        echo "paths=$PATHS" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run mypy
      run: |
        echo "Type checking: ${{ steps.paths.outputs.paths }}"
        uv run mypy ${{ steps.paths.outputs.paths }}
      shell: bash