name: Build Package
description: Build the Python package using uv

inputs:
  import-module:
    description: "Python module name to test importing"
    required: true
    default: ""

runs:
  using: composite
  steps:

    - name: Check if this is a package repo
      id: check
      run: |
        if [ -n "${{ inputs.import-module }}" ]; then
          echo "is_package=true" >> "$GITHUB_OUTPUT"
        else
          echo "is_package=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Build Package
      if: ${{ steps.check.outputs.is_package == 'true' }}
      run: uv build
      shell: bash
    - run: |
        uv run python - <<EOF
        import importlib
        importlib.import_module("${{ inputs.import-module }}")
        print("Package imported successfully")
        EOF
      name: Test import package
      if: ${{ steps.check.outputs.is_package == 'true' }}
      shell: bash
