name: Run Tests
description: Run pytest

runs:
  using: composite
  steps:
    - name: Check for tests directory
      id: check_tests
      run: |
        if [ -d "tests" ]; then
          echo "has_tests=true" >> $GITHUB_OUTPUT
        else
          echo "has_tests=false" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: Run pytest with coverage (safe)
      if: ${{ steps.check_tests.outputs.has_tests == 'true' }}
      run: |
        THRESHOLD=${COVERAGE_THRESHOLD}

        CMD="uv run pytest --cov=src --cov-report=term"

        if [ "$THRESHOLD" -gt 0 ]; then
          CMD="$CMD --cov-fail-under=$THRESHOLD"
        fi

        echo "Running: $CMD"
        $CMD || EXIT_CODE=$?

        # Pytest exit code 5 = no tests collected → treat as success
        if [ "${EXIT_CODE}" = "5" ]; then
          echo "No tests collected. Continuing CI."
          exit 0
        fi

        exit ${EXIT_CODE:-0}
      shell: bash

    - name: Skip tests (no tests folder)
      if: ${{ steps.check_tests.outputs.has_tests == 'false' }}
      run: echo "No tests directory found. Skipping tests."
      shell: bash

