name: Run Tests
description: Run pytest

inputs:
  skip-coverage:
    description: 'Skip coverage reporting'
    required: false
    default: false
    type: boolean
runs:
  using: composite
  steps:
    - run: uv run pytest ${{ inputs.skip-coverage == false && '--cov=src' || '' }}
      shell: bash
